### ISSUE TITLE
Responsive, resilient, elastic are desired qualities whereas message-driven is a design approach

### ISSUE THREAD

**Issue by pmerson** [reactivemanifesto/reactivemanifesto#82] opened 2016-03-28 18:54 UTC
The characterization of reactive systems mixes two things:
- Responsive, resilient, and elastic are desired quality attributes of a reactive system. The description is not enlightening. One can argue that those are desired qualities of general distributed systems. 
- Message-driven is the key design approach to be followed in reactive systems. 

Overall, the quality attributes (responsive, resilient, elastic) are _the result_ of employing a message-driven design.

My suggestion: 
- Describe reactive systems as systems that follow a message-driven approach, possibly adding some other constraints to be more specific.
- Add a separate subsection to say what qualities well-designed reactive systems shall exhibit. In here you mention responsive, resilient, elastic. But you could also add: runtime autonomy and loose-coupling.
- Acknowledge that tradeoffs exist.

**Comment by lazaridis-com** [comment] 2016-04-05 10:30
see #48

**Comment by lazaridis-com** [comment] 2016-11-19 18:51
@jboner,  you could close this issue as a duplicate of #48

**Comment by jboner** [comment] 2017-08-15 11:40
I agree with this general assessment. I know that it is not addressing the core of the problem (which is the way the message-driven is presented in the manifesto), but as a first step, I have changed the illustration of the 4 traits in the manifesto to lay them out in three categories: means, form, and value (see the new illustration in the manifesto). The next step would be to reflect this in the manifesto itself. 
@rkuhn WDYT?

**Comment by pmerson** [comment] 2017-08-21 20:22
Not sure what rkuhn thinks, but I think the revised diagram is significantly more expressive. It's a clever depiction of the traits. If the prose gets updated accordingly, one suggestion is to make the meaning of the arrows in the picture clear. 

On a different note: I just noticed that the word "event" does not show up in the manifesto anywhere. I understand the description of message-driven in contrast with event-driven in the glossary. However, I think that description is a peculiar perspective. My perspective: the term event-driven has become widely used to refer to a reactive system where (a) the messaging relies on the publish-subscribe messaging pattern, (b) messages are called events, (c) the communication is effected by an event bus or event manager, and (d) senders and receivers don't know about each other and are hence loosely coupled. Such systems can have receivers (subscribers) that use the push or pull model, though recent designs tend to favor the pull model in support of having dumb pipes. Apache Kafka is an example of event bus that supports such design. 
Anyway, the point is that I think the manifesto should mention events, even if you believe it would only be for the sake of keywords on a web search.

**Comment by jboner** [comment] 2017-09-01 08:32
I agree that it should ideally discuss how it relates to an event-driven model/design. IMO an event-driven model is what you (most often) expose to the user (since it is simpler and less powerful than message-passing, with simpler semantics) while building it on top of a message-driven fabric (which models distribution and communication). This is the story I'm arguing for in my recent book 'Reactive Microsystems'.  

A more general problem is what changes would require a rewrite of the manifesto. It has now been translated into 12 languages and is not that easy to "just update".

**Comment by jboner** [comment] 2018-07-24 19:03
We are updating the illustration to some extent address this issue. See: https://github.com/reactivemanifesto/reactivemanifesto/issues/112

**Closed by jboner** 2018-07-24 19:03 UTC
